import { type NewAuthUser as NewUser, type AuthUser as User, user } from '@muirouter/shared-db/auth';
import {
  type Model,
  models,
  type NewModel,
  type NewOauthClient,
  type NewOauthCode,
  type NewOauthToken,
  type NewRechargeLog,
  type NewSpendingLimit,
  type NewStripeTopupSession,
  type NewUsageLog,
  type NewUsageStat,
  type NewVideoGenerationJob,
  type NewWallet,
  type OauthClient,
  type OauthCode,
  type OauthToken,
  oauthClients,
  oauthCodes,
  oauthTokens,
  type RechargeLog,
  rechargeLogs,
  type SpendingLimit,
  type StripeTopupSession,
  spendingLimits,
  stripeTopupSessions,
  type UsageLog,
  type UsageStat,
  usageLogs,
  usageStats,
  type VideoGenerationJob,
  videoGenerationJobs,
  type Wallet,
  wallets,
} from '@muirouter/shared-db/business';

// 向后兼容 app 侧既有命名；底层已切到 better-auth 的 user 表。
export const users = user;

export {
  models,
  oauthClients,
  oauthCodes,
  oauthTokens,
  rechargeLogs,
  spendingLimits,
  stripeTopupSessions,
  usageLogs,
  usageStats,
  videoGenerationJobs,
  wallets,
};

export type {
  Model,
  NewModel,
  NewOauthClient,
  NewOauthCode,
  NewOauthToken,
  NewRechargeLog,
  NewSpendingLimit,
  NewStripeTopupSession,
  NewUsageLog,
  NewUsageStat,
  NewVideoGenerationJob,
  NewWallet,
  OauthClient,
  OauthCode,
  OauthToken,
  RechargeLog,
  SpendingLimit,
  StripeTopupSession,
  UsageLog,
  UsageStat,
  VideoGenerationJob,
  User,
  NewUser,
  Wallet,
};
